name: klaws
description: Extractor for Raven
version: 1.0.0

environment:
  sdk: ^3.8.0-24.0.dev

dependencies:
  dio: ^5.9.0
  html: ^0.15.6
  intl: ^0.20.2
  json_path: ^0.8.0
  path: ^1.9.1
  json_annotation: ^4.9.0
  archive: ^4.0.7
  path_provider: ^2.1.5
  xayn_readability_core:
    git:
      url: https://github.com/xaynetwork/xayn_readability_core
  objectbox: ^5.0.2

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.11.1
  lints: ^6.0.0
  objectbox_generator: any
  test: ^1.27.0
